name: deploy_docker_image_wordpress
on:
  workflow_dispatch:
    inputs:
      image_version:
    

jobs:
  greet:
    runs-on: self-hosted

    steps:
      - name: my-step
        working-directory: /home/digtal_ocean
        run: |
          echo $color
          echo $Number
          echo ${{ env.region }}
          export IMAGE_VERSION=${{ github.event.inputs.image_version }}
          echo $IMAGE_VERSION
          docker-compose pull wordpress
          docker-compose up -d
      - name: echo
        run: echo "${{ github.event.inputs.image_version }} "
