name: test
on:
  workflow_dispatch:
    inputs:
      image_version:
    

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.image_version }} "
