# this is pipeline for test
name: hello-world
on: push

jobs:
  build-image-4-wordpress:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone https://github.com/yevheniistelmakh/lasttry.git
      - name: rebuild-wordpress-image
        run: |
          ls -la
          pwd
          ls -la
          pwd
          docker build -t yevhenii1991/wordpress /.
          docker build -t yevhenii1991/wordpress:${{ github.sha }} /.
      - name: login-push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker logout
          docker login -u 
          docker push  yevhenii1991/wordpress:${{ github.sha }}
          docker push yevhenii1991/wordpress:latest
  
  my-job:
    runs-on: self-hosted
    needs: build-image-4-wordpress
    env:
      color: red
      region: central
      Number: build number ${{ github.sha }}
    steps:
      - name: my-step
        working-directory: /home/digtal_ocean
        run: |
          echo $color
          echo $Number
          echo ${{ env.region }}
          export IMAGE_VERSION=90
          echo $IMAGE_VERSION
          docker-compose pull wordpress
          docker-compose up -d
          pwd
     
