# this is pipeline for test
name: hello-world
on: push

jobs:
  my-job:
    runs-on: self-hosted
    env:
      color: red
      region: central
      Number: build number ${{ github.sha }}
    steps:
      - name: my-step
        working-directory: /home/digtal_ocean
        run: |
          echo $color
          echo $Number
          echo ${{ env.region }}
          export IMAGE_VERSION=90
          echo $IMAGE_VERSION
          
          pwd
     
