# this is pipeline for test
name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        working-directory: /home/digtal_ocean
        run: |
          export IMAGE_VERSION=latest
          pwd
          echo $IMAGE_VERSION
          docker-compose stop
          docker-compose up -d
          pwd
     
