# this is pipeline for test
name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          pwd
          cd /home/digtal_ocean
          pwd
          docker-compose restart
      - name: docker ps
        run: docker-compose version
