# this is pipeline for test
name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        working-directory: /home/digtal_ocean
        run: |
          pwd
          docker-compose up 
      - name: docker_PS
        run: docker-compose version
